//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.Expends_Report = new HashSet<Expends_Report>();
            this.Orders = new HashSet<Orders>();
            this.Provider_Details = new HashSet<Provider_Details>();
        }

        public employee(employee e)
        {
            this.Id_Employee = e.Id_Employee;
            this.id_number = e.id_number;
            this.name = e.name;
            this.phone = e.phone;
            this.Gender_Id = e.Gender_Id;
            this.employee_type_id = e.employee_type_id;
            this.postal_code_id = e.postal_code_id;
            this.deleted = e.deleted;
        }

        public int Id_Employee { get; set; }
        public string id_number { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public int Gender_Id { get; set; }
        public int employee_type_id { get; set; }
        public int postal_code_id { get; set; }
        public string deleted { get; set; }
    
        public virtual employee_type employee_type { get; set; }
        public virtual Postal_Code_Worker Postal_Code_Worker { get; set; }
        public virtual Workers_Gender Workers_Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expends_Report> Expends_Report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider_Details> Provider_Details { get; set; }
    }
}
