//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expends_Report
    {
        public int Id_Expends_Report { get; set; }
        public int expends_type_id { get; set; }
        public string note { get; set; }
        public System.DateTime date { get; set; }
        public int value { get; set; }
        public int employee_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual Expends_Type Expends_Type { get; set; }
    }
}
