//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machines
    {
        public int Id_Machines { get; set; }
        public string kind { get; set; }
        public string Manufacture_Department { get; set; }
        public int work_shifts_id { get; set; }
        public string Deleted { get; set; }
    
        public virtual Work_Shifts Work_Shifts { get; set; }
    }
}
